name: Install and Execute ASCII 
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and download repos
        uses: actions/checkout@v4

      - name: Install COWSAY
        run: sudo apt-get install cowsay -y

      - name: Execute COWSAY
        run: COWSAY -f dragon " run run Iam coming" >> dragon.txt

      - name: list the files
        run: ls -ltra

      - name: Read files
        run: cat dragon.txt